[package]
name = "manga"
version = "0.2.0"
authors = ["Hentioe_Cl <me@bluerain.io>"]
edition = "2018"

[dependencies]
libcore = { path = "../libcore" }
clap = "2.32.0"
failure = "0.1.5"
indicatif = "0.11.0"
env_logger = "0.6.0"
log = "0.4.6"
lazy_static = "1.2.0"
regex = "1.1.0"
console = "0.7.3"
scan_dir = "0.3.3"